//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_LaRondeDesFacs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borne
    {
        public string user_id { get; set; }
        public int nb_passage { get; set; }
        public System.DateTime temps { get; set; }
        public int borne_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
