//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_LaRondeDesFacs
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Borne = new HashSet<Borne>();
        }
    
        public string user_id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime date_naissance { get; set; }
        public string faculte { get; set; }
        public string promotion { get; set; }
    
        public virtual ICollection<Borne> Borne { get; set; }
    }
}
